name: Release drafter

on: workflow_dispatch

permissions:
  contents: read

jobs:
  draft_release:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Read version
        id: read_version
        run: |
          echo "version=$(cat version/VERSION | tr -d '[:space:]')" >> $GITHUB_OUTPUT
      - name: Print version
        run: |
          echo ${{ steps.read_version.outputs.version }}
      - uses: release-drafter/release-drafter@v6
        id: release
        with:
          version: ${{ steps.read_version.outputs.version }}
          name: v${{ steps.read_version.outputs.version }}
          tag: v${{ steps.read_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_and_publish:
    runs-on: macos-latest
    needs: draft_release
    permissions:
      contents: write
      pull-requests: write
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TAG_NAME: ${{ needs.draft_release.outputs.tag_name }}
      CGO_ENABLED: 0
    steps:
      - uses: actions/checkout@v4
      - name: Build App x86_64
        uses: sersoft-gmbh/xcodebuild-action@v3
        with:
          project: SpoofDPI App.xcodeproj
          scheme: SpoofDPI App
          arch: x86_64 
          destination: platform=macOS
          derived-data-path: ./build
          action: build
      # - name: Save App
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: SpoofDPI App.app
      #     path: ./build/Build/Products/Debug/SpoofDPI App.app
      - name: Upload to Release
        run: | 
          tar -zcvf "SpoofDPI App-$TAG_NAME-x86_64.tar.gz" ./build/Build/Products/Debug/SpoofDPI\ App.app
          gh release upload $TAG_NAME "SpoofDPI App-$TAG_NAME-x86_64.tar.gz"
      - uses: actions/checkout@v4
      - name: Build App arm64
        uses: sersoft-gmbh/xcodebuild-action@v3
        with:
          project: SpoofDPI App.xcodeproj
          scheme: SpoofDPI App
          arch: arm64 
          destination: platform=macOS
          derived-data-path: ./build
          action: build
      # - name: Save App
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: SpoofDPI App.app
      #     path: ./build/Build/Products/Debug/SpoofDPI App.app
      - name: Upload to Release
        run: | 
          tar -zcvf "SpoofDPI App-$TAG_NAME-arm64.tar.gz" ./build/Build/Products/Debug/SpoofDPI\ App.app
          gh release upload $TAG_NAME "SpoofDPI App-$TAG_NAME-arm64.tar.gz"